### ISSUE TITLE
Unable to extract the watermark

### ISSUE THREAD

**Issue by mbrijun** [guofei9987/blind_watermark#100]
Hi, when I am trying to extract the watermark, I am getting the following error message. Please kindly point me in the right direction. Thank you.

```
>>> wm_extract = bwm2.extract(img2, wm_shape=len_wm, mode='str')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "O:\OneDrive\Documents\DESIGN\Website\venv\lib\site-packages\blind_watermark\blind_watermark.py", line 105, in extract
    byte = ''.join((np.round(wm)).astype(np.int).astype(np.str))
  File "O:\OneDrive\Documents\DESIGN\Website\venv\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
```

**Comment by yuningzhang2022** [comment]
Hi, it might be useful to downgrade numpy. For example, `pip install-U numpy==1.19.0`.

**Comment by mbrijun** [comment]
@yuningzhang2022  - thank you very much for responding. Your advice was accurate. It works fine with Numpy 1.19.5. It appears that Numpy 1.20 deprecated aliases for built in types, which seems to cause issue. https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

**Comment by yuningzhang2022** [comment]
You're welcome!

**Comment by guofei9987** [comment]
Thank you!
Bug fixed in version 0.4.4
